CREATE TABLE [dbo].[tblDistributors]
(
	DistributorGuid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() RowGuidCol PRIMARY KEY,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	Name NVARCHAR(255) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	Email NVARCHAR(255) NOT NULL,
	ContactNumber NVARCHAR(50) NOT NULL,
	PhysicalAddress NVARCHAR(255) NULL,
	ReceiveMontly BIT NOT NULL DEFAULT 0,
	ReceiveQuaterly BIT NOT NULL DEFAULT 0,
	ReceiveHalfYearly BIT NOT NULL DEFAULT 0,
	ReceiveYearly BIT NOT NULL DEFAULT 0
)
