CREATE TABLE [dbo].[tblMovieTime]
(
	TimeId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() RowGuidCol PRIMARY KEY,
	[Time] TIME NOT NULL,
	[Date] DATE NOT NULL,
	MovieId UNIQUEIDENTIFIER NOT NULL REFERENCES [tblMovies](MovieId),
	NumViewers INT NOT NULL DEFAULT 0
)
