CREATE TABLE [dbo].[tlnkScreenMovie]
(
	linkId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() RowGuidCol PRIMARY KEY,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	MovieId UNIQUEIDENTIFIER NOT NULL REFERENCES [tblMovies](MovieId),
	ScreenId UNIQUEIDENTIFIER NOT NULL REFERENCES [tblScreen](ScreenId),
	StartScreen DATETIME NOT NULL,
	EndScreen DATETIME NOT NULL,
	BookedNum INT NOT NULL DEFAULT 0
)
