CREATE TABLE [dbo].[tlnkScreenMovie]
(
	linkId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() RowGuidCol PRIMARY KEY,
	MovieId UNIQUEIDENTIFIER NOT NULL REFERENCES [tblMovies](MovieId),
	ScreenId UNIQUEIDENTIFIER NOT NULL REFERENCES [tblScreen](ScreenId),
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	StartScreen DATETIME NOT NULL,
	EndScreen DATETIME NOT NULL
)
