CREATE TABLE [dbo].[tlnkMovieDistributor]
(
	linkId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID() RowGuidCol PRIMARY KEY,
	MovieId UNIQUEIDENTIFIER NOT NULL REFERENCES [tblMovies](MovieId),
	DistributorId UNIQUEIDENTIFIER NOT NULL REFERENCES [tblDistributors](DistributorGuid),
	Created DATETIME NOT NULL DEFAULT GETDATE()
)
